name: Flutter Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-0 libblkid1 liblzma5 libwebkit2gtk-4.1-dev libsecret-1-dev
          version: 1.0
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: 3.29.1
      
      - name: Enable desktop support
        run: flutter config --enable-linux-desktop
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build executable
        run: flutter build linux
        shell: bash
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: ./frontend/build/linux/x64/release/bundle/**
  
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: 3.29.1
      
      - name: Enable desktop support
        run: flutter config --enable-windows-desktop
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build executable
        run: flutter build windows
        shell: bash
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: ./frontend/build/windows/x64/runner/Release/**
  
  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: build-linux
          path: linux-artifacts
      
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: build-windows
          path: windows-artifacts
      
      - name: Zip artifacts
        run: |
          zip -r linux-build.zip linux-artifacts
          zip -r windows-build.zip windows-artifacts
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-build.zip
            windows-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
